version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
    working_directory: ~/project
    environment:
      DOCKER_BUILDKIT: 1
jobs:
  setup:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache py3-pip
            pip3 install docker-compose
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up --build -d
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup