version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
    working_directory: ~/project
    environment:
      DOCKER_BUILDKIT: 1
jobs:
  setup:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build frontend Image
          command: docker build -t columbia-registry.spektrum.media/newsmanagementfrontend:prod .
      - run:
          name: Build backend Image
          command: docker build -t columbia-registry.spektrum.media/newsmanagementbackend:prod ./NewsApi
      - run:
          name: Push frontend Image
          command: docker push columbia-registry.spektrum.media/newsmanagementfrontend:prod
      - run:
          name: Push backend Image
          command: docker push columbia-registry.spektrum.media/newsmanagementbackend:prod
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          filters:
            branches:
              only:
                - master